spring:
  application:
    name: RoofParser
  profiles:
    active: ${SPRING_PROFILE}
  datasource:
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
  data:
    jdbc:
      dialect: postgresql
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-message: always
    include-binding-errors: always
  port: ${PORT}